### ISSUE TITLE
problem with list rendering

### ISSUE THREAD

**Issue by gcman105** [thoughtbot/bitters#112]
What is **&%** in the following?

```
&%default-ul {
  list-style-type: disc;
  margin-bottom: $base-spacing / 2;
  padding-left: $base-spacing;
}

&%default-ol {
  list-style-type: decimal;
  margin-bottom: $base-spacing / 2;
  padding-left: $base-spacing;
}
```

 It does not seem to end up in the comiled css file.

**Comment by jb510** [comment]
This is confusing me too.

My assumption (which I'm starting to think is wrong) based on the biitters example page is that 
```
ul,
ol {
  list-style-type: none;
  margin: 0;
  padding: 0 0 0  $base-spacing;
  &%default-ul {
    list-style-type: disc;
    margin-bottom: $small-spacing;
    padding-left: $base-spacing;
  }

  &%default-ol {
    list-style-type: decimal;
    margin-bottom: $small-spacing;
    padding-left: $base-spacing;
  }
}
```
would compile to
```

ul,ol {
  margin: 0;
  padding: 0;
  list-style-type: none
}

ul.default {
  list-style-type: disc;
  margin-bottom: 0.75em;
  padding-left: 1.5em
}

ol.default {
  list-style-type: decimal;
  margin-bottom: 0.75em;
  padding-left: 1.5em
}
```
That CSS is what is in the example page's style sheet, but _not_ what I'm getting from bitters which is just
```
ul,
ol {
  list-style-type: none;
  margin: 0;
  padding: 0 0 0 1.5em; }
```

I'm guessing the SCSS for the example page _actually_ looks like this, not what's in the repo:
```
ul,
ol {
  list-style-type: none;
  margin: 0;
  padding: 0 0 0  $base-spacing;
  &%default-ul {
    list-style-type: disc;
    margin-bottom: $small-spacing;
    padding-left: $base-spacing;
  }

  &%default-ol {
    list-style-type: decimal;
    margin-bottom: $small-spacing;
    padding-left: $base-spacing;
  }
}

ul.default {
  @extend %default-ul;
}

ol.default {
  @extend %default-ol;
}
```
Yes?

**Comment by jb510** [comment]
For newbies it'd help if this was better explained, or if bitters _lists.scss was actually what was used on the example page.

**Comment by kylefiedler** [comment]
@jb510 The Bitters `_lists.scss` is what is being used on the example page. When using a placeholder selector, selectors that start with `%` Sass won't compile the styles till it is extended to another non-placeholder selector. So in this case until you extend `%default-ul` and `%default-ol` there will be no added CSS output. You can look at the example page scss that was linked above here: https://github.com/thoughtbot/bitters/blob/gh-pages/_sass/_example.scss#L5 In order to show those styles we need to add those selectors otherwise they would look just like the other non-styled lists.

I would encourage you to read the documentation on placeholder selectors here: http://sass-lang.com/documentation/file.SASS_REFERENCE.html#placeholder_selectors_

**Comment by jb510** [comment]
Kyle. Thanks. I fully understand how it works. I didn't initially, but as you can see in the sassmeister link above I figured it out.  Do you understand why it is confusing to newbies though?

I, and I suspect many, would assume the example page *just* used _lists.scss.  The output shown on the example page it clearly doesn't.  It uses those extensions (see my sassmeister link above demonstrating the scss that is likely being used on the example page).
