### ISSUE TITLE
Headings are all the same size

### ISSUE THREAD

**Issue by mbesto** [thoughtbot/bitters#153]
I just recently installed bitters on my latest project (having used it for a few months) and notice none of the h1-h6 tags were properly set up for different sizes. You can also see this is the case on the example page:
http://bitters.bourbon.io/example.html

I dug into the code and looks like this different font sizes were changed:

https://github.com/thoughtbot/bitters/commit/324d1db486a5dafbd16ddba8476dc0ac94bc0be1#diff-956b372e3d32f4879e0e77e8cf8daa3cL23

And it looks like all of the h tags 1-6 all have the same `font-size`: (`$base-font-size`)

https://github.com/thoughtbot/bitters/blob/324d1db486a5dafbd16ddba8476dc0ac94bc0be1/app/assets/stylesheets/_typography.scss#L16

cc: @kylefiedler - any idea where you can control different heading sizes with your latest change?

**Comment by kylefiedler** [comment]
@mbesto I normally add in the specific styles for the headings into that typography file as needed or into something like `/components/_primary-header.scss` 

The reason we took them out was because in most of our projects we have to with change or remove those styles. Those defaults didn't really help our cause because of that.

Make sense?

**Comment by mbesto** [comment]
Makes sense, as I am also changing the heading sizes on almost every project. 

But I'm never 'adding' specific styles....simply changing the font-size values in the variables file (`$heading-h1-size`, `$heading-h2-size`, etc). I know very few times where they are all equal so why should that be the case as a default? In other words, the regular pattern is to define all h1-h6 headings and not keep them all the same. If I add a `/components/_primary-header.scss`, it means I'm still inheriting `_typography.scss` which seems to me to have the reverse effect of the fix? Why not drop the font-size all together then? 

PS - Thanks for Bourbon/bitters it's been extremely helpful to my workflow.

**Comment by kylefiedler** [comment]
@mbesto I can see the case for dropping it altogether. Why don't you do a PR and we can get some more people in on this conversation.

**Comment by mbesto** [comment]
Will do. Thanks!

**Comment by Scott-G** [comment]
To be honest this move seems a bit wrong.

Firstly, the change is not very well advertised and had me scratching my head for a few minutes convinced it was a bug either on my side or yours.

Secondly, it seems to go against the whole point of Bitters as I understand it. I thought the idea was to have a nice looking, standard starting point (along with Normalize) 'straight out of the box' that you can easily customise as required. Before, if I wanted to change the heading sizes, I just made a change in variables.scss and it was sorted. Wanting to deal with it outside of Bitters? No problem, I could just comment it out. Now when I create a project I have to add the 6 heading selectors back into typography.scss (or somewhere else). Not a huge task but unnecessary.

I may be missing something but surely having standard defaults that can be easily tweeked when required (or easily commented out/removed) is going to be useful to more people than resetting all to base font size under one selector, meaning everyone has to address this in some way before Bitters is usable?

I fully understand the point of resetting some things, like lists for example. Most of the time they are used with the list style removed anyway and is likely to have different requirements at different points on the same page/site/app so will be reset at a module level. However, the vast majority of the time headings will need to be consistent throughout, so are only set in the base.

Sorry for the rant. I absolutely love the whole Bourbon, Neat, Bitters and Refills 'framework' and it has made a massive difference to my productivity and workflow, so thank you so much for that. I just feel like this is a step in the wrong direction and wanted to voice that opinion.

**Comment by mbesto** [comment]
Hi @Scott-G - I felt the same way. To take on Kyle's perspective, what is your standard way of addressing heading tags with regards to bitters? Do you simply change the variables file settings? (here: https://github.com/thoughtbot/bitters/commit/324d1db486a5dafbd16ddba8476dc0ac94bc0be1#diff-c1cc6c5a0a102aaffd3a987fc8e37f88L7 ) Or do you do an override as Kyle suggested, like `_primary-header.scss`

**Comment by Scott-G** [comment]
Hi @mbesto 
It depends on the project and how much customisation is required.

For very simple projects such as an app front end or very basic site I might use Bitters without many changes at all. This is where it was the most use for me - for quickly setting up tasks with lower aesthetic requirements (usually meaning the customer wants it cheap!) or early prototyping something to show the clients some functionality, whilst knowing I can easily scale up when required,

If it is large, heavily customised project I sometimes don't use Bitters at all. However, the majority of my work lies in the middle where I use Bitters but modify or replace sections as required. Once I have my base set up for all the uniform properties, I then set all the individual section styling using modular SASS sheets in another directory calling variables and mixins etc where required. This gives me efficient code and means I can easily port small or large sections to other projects.

Maybe I am doing this wrong? I have worked on my own for quite a long time now but I try to keep myself as current as I can. My current workflow seems to work great for me but I would always be interested if anyone could point me in a better direction.

**Comment by mermop** [comment]
Starting a new project and also very confused by headings all being the same size - like @Scott-G I find bitters useful for prototyping something without having to write a lot of styles, so needing to manually override for headings to look like headings kind of defeats the point of using it

**Comment by kristianserrano** [comment]
I agree that having to add the styles felt weird. Placing a variable change for $modular-scale-ratio above the font-sizes for the different heading levels is how I handled it, and it could be an easy default. It's easy to do, but annoying to have to do it when setting up a new project. Changing the font sizes would be much easier.

**Comment by jerbens** [comment]
To add default sizes in a quick manner, go to the typography.scss module and use the **modular scale function** in a for loop :

    @for $i from 1 through 6 {
      h#{$i} {
        font-size: modular-scale(6 - $i);
      }
    }

Here, it uses the default $modular-scale-ratio (1.333) and the default $modular-scale-base (1em).
It goes from h1 being ~4.2em in size to h6 being 1em (the scale base).

You can play with the scale using a different ratio and/or base like this :

    font-size: modular-scale((6 - $i), 1em, 1.2);

Using a smaller ratio will result in a shorter range of sizes between h1 and h6, with h6 still being 1em .

**Comment by kristianserrano** [comment]
That's pretty slick, jerbens. I think a less automated version is still needed. For example, in one project, I skip a level between h3 and h2, and again between h2 and h1. Sure, I could put conditions in your solution, but that's a custom thing. Just having the list written out would be a fine and simple solution.

**Comment by jerbens** [comment]
I agree with you that going through each heading is still required for a lot of projects. And that's probably the reason Bitters was made this way, I think. My solution is just a workaround to get some default settings *à la* Bootstrap.

**Comment by tysongach** [comment]
A re-post of my comment over on Issue #171:

We made all of the heading sizes the same because Bitters has been specifically designed for use within web applications, which is what we build most of at thoughtbot.

In the context of user interfaces, we still use headings in the markup for the sake of semantics, but we like to begin with a baseline font size and then use a component-based approach to change sizing depending on the purpose.

That being said, we built Bitters to serve our own needs and hope that others find it useful, but please feel free to fork it and tweak it to fit your own needs!

@Scott-G We didn’t do a good job clearly stating this change when we did it; sorry about that. In the future, we’ll try to be more diligent with release notes pointing these things out.

**Comment by kristianserrano** [comment]
That actually makes a lot more sense now that I've begun development of my own pattern library as well. There are a lot of components that have headings within them, and it's never clear what font size a heading in a given component might be. I now see the preset values as a sort of reset, and it makes more sense. Taking the styles I defined with modular scale and putting it under a class name for the main content area will be the better solution for this case.

**Comment by azzcatdesign** [comment]
Thanks for the function tip @jeremyben!

**Comment by robhadfield** [comment]
:+1:  I came here with the same query - glad you were here @jeremyben.

I also reverse the ul, ol styles so that the padded / margin versions are default.

**Comment by joallard** [comment]
I was bothered by this when I first installed Bitters a year ago, and here I am again on the second project that I need to get started quick, this is still a stumbling block. In between the little tasks that hinder my motivation and slow down my productivity, add a gem here, change a default here, convert some files, I wanna get started quick on CSS no fuss, install Bourbon Neat Bitters, why are h1-h6 not styled properly again? Another paper cut instead of doing the rewarding things.

On the substance, h1 to h6 have an inherent hierarchy to them. Imagine typesetting a Markdown document. It seems counter to Bitters' mottos "Predefined styles / Built for speed" to have no predefined styles for that. "Quick scaffolding" becomes: 1. Install Bitters, 2. Iterate some CSS, 3. Wonder why h1-h6 aren't out of the box, 4. Google Bitters Github, 5. Go to issues, 6. Search 'headings', 7. Find the right issue, 8. Read, scroll down, scroll, 9. Copy-paste snippet. Excuse the words, but it's not very scaffoldy.

If only we could make this work for both sides with a quick setting, that would be a good compromise.

**Comment by robhadfield** [comment]
It is deliberate @joallard - see https://github.com/thoughtbot/bitters/issues/171#issuecomment-101288679

I use the little loop above and give it a tweak. Once you're happy then save that as your starter pack.

**Comment by joallard** [comment]
And I'm making the point that that choice seems... horrifying, especially considering the raison d'être of Bitters.

**Comment by kristianserrano** [comment]
Compromise? Maybe use the old definition format with the same font size for each heading level ($base-font-size * 1). Then non-thoughtbot developers can replace the multiplier for each heading level. (Or use modular scale as suggested above?)

**Comment by tysongach** [comment]
@joallard So that we can all have a conversation with some purpose, can you give us a bit of context and talk about your project needs? Why is having a scale of heading sizes core to your design?

For a bit history:

- Here’s the original PR that made all headings the same base font size: https://github.com/thoughtbot/bitters/pull/141
- Here’s the PR that kept all headings equal size, but made them slightly larger than the base font size: https://github.com/thoughtbot/bitters/pull/225

To follow-up on a few of your points:

> …why are h1-h6 not styled properly again?

“Styled properly” is super subjective. The headings _are_ styled, it just may not fit your needs. We cannot design for everyone.

> It seems counter to Bitters' mottos "Predefined styles / Built for speed" to have no predefined styles for that.

Again, Bitters _does_ come with styles and as you can see in the screenshot below, the look and feel of HTML elements is quite different with and without it. It boils down to how _you’re_ interpreting predefined and Bitters might not be a perfect fit for everyone.

<img width="1440" alt="screen shot 2016-08-16 at 18 50 56" src="https://cloud.githubusercontent.com/assets/903327/17718514/6596c97a-63e2-11e6-8991-f0ad87ed283f.png">

> Excuse the words, but it's not very scaffoldy.

Bitters is open-source for a reason. We are freely sharing all of our effort making something we find useful. You can totally fork it and make it the scaffold of _your_ dreams.

At thoughtbot, we fire up hundreds of apps that include Bitters out of the box and it works for us. It’s not perfect, and we’re always listening for feedback, changing things, reverting things that we thought was a good idea that turned out not to be…it’ll forever be a work-in-progress. But we do use it _a lot_ and it’s working. Here’s to iterating 🍻.

> And I'm making the point that that choice seems... horrifying, especially considering the raison d'être of Bitters.

Horrifying? Not to get defensive, but we’re real people here, trying to design and build great things. And honestly, I think [we](https://www.instagram.com/thoughtbot/) [do](https://thoughtbot.com/) [alright](https://dribbble.com/thoughtbot).

**Comment by robhadfield** [comment]
From [PR#141](https://github.com/thoughtbot/bitters/pull/141)

> Remove header styles because they always get changed. The initial styles just add overhead to be changed.

If ThoughtBot _did_ add styling for their headers it's hard to imagine they would be suitable for everyone straight out of the box.

**Comment by kristianserrano** [comment]
But it would be easier to change.
