### ISSUE TITLE
_typography.scss has all H tags sized as $base-font-size

### ISSUE THREAD

**Issue by kmh3785** [thoughtbot/bitters#171]
This results in all heading tags being the base body font size. Is this intentional?

![capture](https://cloud.githubusercontent.com/assets/5419324/7484218/64558a30-f343-11e4-886a-5205d95475c8.PNG)

For reference - in earlier versions, the H tags were styled as so:
![capture](https://cloud.githubusercontent.com/assets/5419324/7484302/3426ad66-f344-11e4-9b20-1398803e1a4a.PNG)

**Comment by aeons** [comment]
This is the commit that removed them: 324d1db486a5dafbd16ddba8476dc0ac94bc0be1.

**Comment by rafalwrzeszcz** [comment]
Ok, but why? It's ridiculous to have all headers with same font size - they are different level for a purpose.

**Comment by tysongach** [comment]
Yes, we intentionally made all of the heading sizes the same. This is because Bitters has been specifically designed for use within web applications, which is what we build most of at thoughtbot.

In the context of user interfaces, we still use headings in the markup for the sake of semantics, but we like to begin with a baseline font size and then use a component-based approach to change sizing depending on the purpose.

@rafalwrzeszcz We built Bitters to serve our own needs and hope that others find it useful, but please feel free to fork it and tweak it to fit your own needs!
