### ISSUE TITLE
Allow variables to be overridden 

### ISSUE THREAD

**Issue by maikeldaloo** [thoughtbot/bitters#20]
Hello,

I'm loving bitters so far but one annoyance I have is that I can't override variables without modifying the Bitters source files.

It would be helpful to add !default to all the variables in _variables.scss to allow us to set those variables before the file is loaded, that way Bitters won't override them and use our setting.

This is useful especially when it comes to updating the library - it means that we won't lose any of our changes.

**Comment by lomteslie** [comment]
Is this being considered at all? I think it would be a great option to be able to override variables instead of  editing the library code. I see no problem with overriding variables, as they generate no additional "cruft" in the CSS output. The current implementation also makes upgrading bitters in the future quite a task.

**Comment by kylefiedler** [comment]
@lomteslie No this is not being considered. I think it's important to note that Bitters is a scaffold similar to something like HTML5 Boilerplate. It is not meant as an additional css reset. Because of it's intended use being able to upgrade Bitters would most likely break your styles. For example we are taking out the header font sizes. For people that already have Bitters installed if they upgraded this new version would break all of the header styles on their site.

For more of a discussion around this see this PR: https://github.com/thoughtbot/bitters/pull/32
