### ISSUE TITLE
get rem values

### ISSUE THREAD

**Issue by mmjaeger** [thoughtbot/bitters#236]
Hello
Just installed bourbon and bitters - it creates em values for h1, h2, h3, etc. - what do I need to do to get rem values?

Thank you in advance for your input.

**Comment by tysongach** [comment]
@mmjaeger Hi! Are you speaking about all heading elements being set with the `modular-scale`: https://github.com/thoughtbot/bitters/blob/master/core/_typography.scss#L15 ?

**Comment by mmjaeger** [comment]
exactly

**Comment by tysongach** [comment]
@mmjaeger The `modular-scale` only supports ems, so I’d suggest swapping `font-size: modular-scale(1);` for `font-size: 1.2rem;` or whatever value you like. Keep in mind, Bitters is just a starting point, so feel free to customize as you wish. In this case swapping for rems instead of ems to fit your needs is :+1:

**Comment by mmjaeger** [comment]
Thanks - as to Neat - is there a version 2.0 that working yet - any flex box code you could suggest that would work with Neat

**Comment by tysongach** [comment]
@mmjaeger We’re actively working on Neat 2.0…no news yet.
