### ISSUE TITLE
Version Why?

### ISSUE THREAD

**Issue by rwboyer** [thoughtbot/bitters#238]
Curious as to why bitters 1.3.1 which is a "release" and what gets installed by default via gem, npm, bower, whatever depends on v5 bourbon (and breaks without it) when v5 is not released?

Any particular standard canonical recommendation for this besides making sure to install v1.20 for new projects that happen to be using the current "release" of bourbon?

**Comment by tysongach** [comment]
@rwboyer Sorry for the confusion; we probably could’ve been more clear with the `1.3` release. Bourbon 5—though in beta—is solid and we’ve been using the two together internally for awhile. It’s hard for Bitters to align to SemVer because nearly every change would be a breaking change, but we should establish something to better set expectations.

That being said, we don’t publish to npm or Bower. And when using the gem, the Bitters files should installed right into the project and easy to change. I believe if you want to use `1.3` with Bourbon `4.x`, you just need to swap `$font-stack-system` with `$helvetica`.

Is there any particular issue I can help with, maybe with Bourbon 5 or something else?

**Comment by rwboyer** [comment]
@tysongach 

Thanks for the response... 

actually there is something unrelated. Love bourbon, but am not crazy familiar with neat. and was just messing with a quick test port of a smallish port of a foundation 5.5 project over to neat to see how it plays. One strange thing which is bugging me, probably simple and stupid is this...

outer does an @include outer-container

two divs inside then do an @include span-columns(x) and @include span-columns(y) = stupidly simple.

My expected behavior is if x + y = 12 they are on same "row" what I see is if x + y = 12 the last one goes to next row. UNLESS I add an @include omega() to the last one which bumps it up to the same row. So I need an @include omega() even if x+y = 12???? not what I expected from the docs unless of course I am doing something wrong but it's super simple and even took it out of the test port I'm doing.

Thanks

RB

**Comment by rwboyer** [comment]
@tysongach 

Ps. I use foundation semantically via sass on all our stuff SO... it should be a fairly simple port considering theres no small-this and large-that classes all over the place... was just comparing using neat + bourbon for smaller projects that don't need the giant raft of crap and also looking at it as an alternative to foundation 6 which has a lot less cruft (allegedly)

**Comment by tysongach** [comment]
@rwboyer No problem. Can you please [file an issue over on the Neat repo](https://github.com/thoughtbot/neat/issues/new) regarding your question and provide a CodePen or similar of the code not working? That way we can be sure we are understanding the issue and can provide the most help.

Regarding Foundation and classes: Bourbon, Neat and Bitters don’t output classes at all. We’re really not a framework like Foundation is, but more of a toolset to help you author your stylesheets a bit easier and hopefully help make them more maintainable.

**Comment by pythonlabsstudent** [comment]
@tysongach that's why I started using these three 'tools' over Foundation or Bootstrap. I am trying to learn to be a front-end guy and since those Frameworks seem to kind of baby feed me into doing lots of stuff without KNOWING what I'm doing (precisely) then I needed to look elsewhere and that's what brought me to your toolset. It looks amazing and I'm excited to keep learning about them :))

**Comment by facelesspanda** [comment]
I'm still wondering why a "solid" and "stable" version is still a beta pre-release on the bourbon repo when it's a dependency on this one. If it's solid, why not release it? Simply waiting for a satisfying milestone to call it "5.0.0", or is there a more understandable reason?

**Comment by tysongach** [comment]
@facelesspanda We’re working on the documentation.

**Comment by misterhtmlcss** [comment]
@tyson respectfully this seems to be causing issues. I know that this kind of work is done mostly on someone's free time, but somewhere along the way a line needs to be drawn. This is a communication issue, not an effort or documentation issue that can be easily solved. Additionally documents can be easily sourced from the community so it's not all born by you guys. Surely there are lots of 'beta' installs and those are people that can be called upon for assistance on this very issue. 
Just think about it please.
