### ISSUE TITLE
Button: `white-space` set to `nowrap`

### ISSUE THREAD

**Issue by nickngqs** [thoughtbot/bitters#281]
Just curious, what's the purpose of white-space no wrap for button elements. Is there a specific problem it's solving?

I'm asking because sometimes the text inside a button gets too long and overlaps happens. With white-space: normal, at least there's a fallback (the text will overflow to the next line, expanding the button instead)

I might take out the white-space: nowrap property in my projects, but just curious if it will affect something else that I'm unaware of

**Comment by tysongach** [comment]
Hi! That’s a good question.

I did some digging and found that the property was added to the button styles [in this commit](https://github.com/cwardzala/bitters/commit/bdf024e7e5b42245bf324d272bde61af20dc1240), but no explanation as to why.

My hunch is two-fold:

1. Generally speaking, we typically want single-line text in buttons. If a button is too wide because of its contents, or its text breaks onto multiple lines, I essentially consider it a bug and try to get it back to one line. This could mean re-wording the text to be more succinct.
1. Without `white-space: nowrap;`, the text inside the button can wrap in unexpected ways due to its placement in particular contexts, even if the text is not all that long. For example, when its parent is set to `display` `flex`. I made [a quick-and-dirty CodePen to illustrate](http://codepen.io/tysongach/pen/ZKELOq?editors=1100).
